version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: house-backend
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
    - .:/app
    depends_on:
      - db

  db:
      image: postgres:14.3
      ports:
          - "5432:5432"
      restart: unless-stopped
      container_name: house-db
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      volumes:
          - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
