version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: house-backend
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
    - .:/app
    depends_on:
      - db

  db:
    image: postgres:14.3
    ports:
      - "5432:5432"
    restart: unless-stopped
    container_name: house-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
        - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: house-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./redis/:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: house-celery
    command: celery -A house worker -l info
    volumes:
      - .:/app
    depends_on:
    - redis
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: house-celery-beat
    command: celery -A house beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  pgdata: {}
  redis: {}
